### ISSUE TITLE
Any reason why session.vim isn't listed in .gitignore?

### ISSUE THREAD

**Issue by iNamik** [BurntSushi/ty#1]
Just wonderin' :)

**Comment by BurntSushi** [comment]
Probably just due to laziness. I sometimes work on multiple machines and it's nice to just have the `session.vim` file sitting there waiting for me. Although I think all of my `session.vim` files are the same, so I could probably put it somewhere else. I'll leave this issue open until I do that. Thanks for the poke. :-)

**Comment by iNamik** [comment]
Hey looks like this never got fixed :)  I'm closing out some old open issues.  Happy 2021!
